Shannon-Data/ShannonBase

README
mysql-test/include/have_shannon_rapid.inc
storage/rapid_engine/CMakeLists.txt
storage/rapid_engine/ha_shannon_rapid.cc

use : '-DWITH_SHANNON_RAPID_SECONDARY_STORAGE_ENGINE=1' in cmake config

feat(rapid): Makes rapid engine mandatory

---

storage/rapid_engine/CMakeLists.txt
storage/rapid_engine/COPYING.shannon-data
storage/rapid_engine/compress/dictionary/dictionary.cpp
storage/rapid_engine/compress/dictionary/dictionary.h
storage/rapid_engine/handler/ha_shannon_rapid.cc
storage/rapid_engine/handler/ha_shannon_rapid.h
storage/rapid_engine/imcs/cu.cpp
storage/rapid_engine/imcs/cu.h
storage/rapid_engine/imcs/imcs.cpp
storage/rapid_engine/imcs/imcs.h
storage/rapid_engine/imcs/imcu.cpp
storage/rapid_engine/imcs/imcu.h
storage/rapid_engine/imcs/readme.txt
storage/rapid_engine/persistence/persistence.h
storage/rapid_engine/populate/populate.h
storage/rapid_engine/readme.txt
storage/rapid_engine/recovery/recovery.h
storage/rapid_engine/resource_management/resw_mgmt.h
storage/rapid_engine/utils/utils.h

Adds some infra types and system vars, status vars.

feat(rapid): Adds the infra types

---

share/messages_to_clients.txt
share/messages_to_error_log.txt
sql/dd/dd_table.cc
sql/sql_table.cc
sql/sql_table.h
storage/rapid_engine/handler/ha_shannon_rapid.cc
storage/rapid_engine/imcs/imcs.cpp
storage/rapid_engine/imcs/imcs.h

feat(rapid): load table support

---

sql/sql_table.cc
sql/sql_table.h
storage/perfschema/CMakeLists.txt
storage/perfschema/pfs_engine_table.cc
storage/perfschema/table_rpd_column_id.cc
storage/perfschema/table_rpd_column_id.h
storage/perfschema/table_rpd_columns.cc
storage/perfschema/table_rpd_columns.h
storage/rapid_engine/handler/ha_shannon_rapid.cc

Adds `rpd_columns` and `rpd_columns_id` to performance_schema as Heatawave does. which is used to trace the loaded table information.

feat(rapid): Adds system table to keey rapid info

---

sql/sql_table.cc
sql/sql_table.h
storage/perfschema/CMakeLists.txt
storage/perfschema/table_rpd_columns.cc
storage/perfschema/table_rpd_columns.h
storage/perfschema/table_rpd_preload_stats.cc
storage/perfschema/table_rpd_preload_stats.h
storage/perfschema/table_rpd_table_id.cc
storage/perfschema/table_rpd_table_id.h
storage/perfschema/table_rpd_tables.cc
storage/perfschema/table_rpd_tables.h
storage/rapid_engine/handler/ha_shannon_rapid.cc
storage/rapid_engine/imcs/cu.cpp
storage/rapid_engine/imcs/cu.h
storage/rapid_engine/imcs/imcs.cpp
storage/rapid_engine/imcs/imcs.h
storage/rapid_engine/imcs/imcu.cpp
storage/rapid_engine/imcs/imcu.h
storage/rapid_engine/include/rapid_object.h
storage/rapid_engine/include/rapid_stats.h
storage/rapid_engine/ml/readme.txt

Part1: part of loading data into rapid
Part2: meta infomration table.

feat(shannon): load data into rapid-imcs

---

storage/rapid_engine/imcs/cu.cpp
storage/rapid_engine/imcs/cu.h
storage/rapid_engine/imcs/imcu.cpp
storage/rapid_engine/imcs/imcu.h

some minor changes(initialization some objects) for load-table.

feat(hotfix): hot fix of load table into imcs

---

storage/rapid_engine/CMakeLists.txt

Adds  innodb.cmake to rapid directory, which rapid use innodb module more easily.

feat(rapid): minor changes for rapid cmake file

---

share/messages_to_clients.txt
sql/sql_select.cc
storage/rapid_engine/compress/dictionary/dictionary.cpp
storage/rapid_engine/compress/dictionary/dictionary.h
storage/rapid_engine/handler/ha_shannon_rapid.cc
storage/rapid_engine/handler/ha_shannon_rapid.h
storage/rapid_engine/imcs/chunk.cpp
storage/rapid_engine/imcs/chunk.h
storage/rapid_engine/imcs/cu.cpp
storage/rapid_engine/imcs/cu.h
storage/rapid_engine/imcs/imcs.cpp
storage/rapid_engine/imcs/imcs.h
storage/rapid_engine/imcs/imcu.cpp
storage/rapid_engine/imcs/imcu.h
storage/rapid_engine/include/rapid_const.h
storage/rapid_engine/include/rapid_context.h

Adds some framework code for read and write function.

feat(rapid): adds framework for 'read' and 'write' data

---

storage/rapid_engine/handler/ha_shannon_rapid.cc
storage/rapid_engine/imcs/imcs.cpp
storage/rapid_engine/include/rapid_const.h
storage/rapid_engine/populate/populate.cpp
storage/rapid_engine/populate/populate.h

Refine some varaible names make it more readable.

feat(rapid): Changes some variables' name

---

sql/dd_table_share.cc
sql/field.h
sql/sql_const.h
sql/sql_insert.cc
sql/sql_show.cc
storage/innobase/handler/ha_innodb.cc
storage/innobase/row/row0mysql.cc
storage/rapid_engine/handler/ha_shannon_rapid.cc
storage/rapid_engine/imcs/chunk.cpp
storage/rapid_engine/imcs/cu.cpp
storage/rapid_engine/imcs/imcs.cpp
storage/rapid_engine/include/rapid_const.h

1: in getting trxid, we use a ghost column, which will not used in insertion statement.
2: in selection statment, do thong with ghost column.
3: fixed up unit of imcs.

feat(shannon): fixed up some bugs in insertion

---

sql/field.cc
sql/field.h
sql/sql_table.cc
storage/rapid_engine/compress/dictionary/dictionary.cpp
storage/rapid_engine/compress/dictionary/dictionary.h
storage/rapid_engine/handler/ha_shannon_rapid.cc
storage/rapid_engine/imcs/cu.cpp
storage/rapid_engine/include/rapid_context.h

Adds column encoding info for meta table pfs.rpd_columnxx

feat(rapid): adds info for column encodig

---

storage/innobase/handler/ha_innodb.cc
storage/rapid_engine/handler/ha_shannon_rapid.cc
storage/rapid_engine/imcs/cu.cpp
storage/rapid_engine/imcs/imcs.cpp

Adds datetime, decimal, et.al types.

feat(rapid): more data types supported

---

sql/dd_table_share.cc
sql/field.h
sql/filesort.cc
sql/sql_base.cc
sql/sql_table.cc
sql/sql_update.cc
storage/innobase/handler/ha_innodb.cc
storage/innobase/row/row0sel.cc

fix bugs in sql layer, skip the ghost column.

feat(shannon): fix bugs in sql

---

sql/auth/sql_authorization.cc
sql/item.cc
sql/sql_base.cc
sql/sql_insert.cc
sql/table.cc
sql/table_trigger_dispatcher.cc
storage/csv/ha_tina.cc

fix bugs to skip the ghost column in sql to make sure all mysql-tests are runable.

feat(shannon): fix bugs for mysql-test

---

sql/dd_table_share.cc
sql/default_values.cc
sql/sql_const.h
sql/sql_executor.cc
storage/innobase/row/row0sel.cc

fix up assertion failed in 'row_prebuilt_free', use incorrect trx_id length in 'row_sel_field_store_in_mysql_format_func'

feat(shannon): fix drop table corruption

---

sql/opt_explain.cc
sql/sql_tmp_table.cc

fixed up wrong displayed read data size in explaination.

feat(shannon): fix explain shows incorrect read data size

---

mysql-test/collections/disabled.def
mysql-test/r/alter_table.result
mysql-test/r/explain_json_all.result
mysql-test/r/explain_json_none.result
sql/dd_table_share.cc
sql/default_values.cc
sql/field.cc
sql/field.h
sql/sql_base.cc
sql/sql_executor.cc
sql/sql_partition.cc
sql/sql_table.cc
sql/table.cc
sql/table.h
storage/innobase/handler/ha_innodb.cc
storage/innobase/row/row0sel.cc
storage/perfschema/table_prepared_stmt_instances.cc

some changes for making mysql-test-run runnable.

feat(shannon): to make mtr runable

---

mysql-test/collections/disabled.def
mysql-test/r/archive.result
sql/dd_table_share.cc
sql/sql_executor.cc
sql/table.cc
sql/table.h
storage/innobase/handler/ha_innodb.cc
storage/innobase/handler/handler0alter.cc
storage/myisam/ha_myisam.cc

disable some mtr cases temporaryly, and fix alter table crash

feat(shannon): to support mtr

---

mysql-test/r/create.result
mysql-test/r/information_schema_cs.result
mysql-test/r/information_schema_statistics.result
mysql-test/r/invisible_columns_myisam.result
mysql-test/r/myisam_mrr_cost.result
mysql-test/r/myisam_mrr_cost_all.result
mysql-test/r/myisam_mrr_cost_icp.result
mysql-test/r/myisam_mrr_icp.result
mysql-test/r/myisam_mrr_none.result
mysql-test/r/myisam_optimize_table.result
mysql-test/r/mysqld--help-notwin.result
mysql-test/r/mysqldump_myisam.result
mysql-test/r/opt_costmodel_restart_myisam.result
mysql-test/suite/secondary_engine/t/shannon_define.test
mysql-test/suite/secondary_engine/t/shannon_install.test
mysql-test/suite/secondary_engine/t/shannon_load.test
mysql-test/suite/secondary_engine/t/shannon_uninstall.test
sql/rpl_record.cc
sql/sql_show.cc

feat(shannon): mtr changes

---

mysql-test/collections/disabled.def
mysql-test/r/grant4_myisam.result
mysql-test/r/myisam.result
mysql-test/suite/innodb/r/innodb.result
storage/innobase/row/row0sel.cc
storage/myisam/ha_myisam.cc

fixed up mtr cases, remove these from disabled file.

feat(shannon): fixed for mtr case

---

storage/rapid_engine/compress/algorithms.cpp
storage/rapid_engine/compress/algorithms.h
storage/rapid_engine/compress/dictionary/dictionary.cpp
storage/rapid_engine/compress/dictionary/dictionary.h
storage/rapid_engine/handler/ha_shannon_rapid.cc
storage/rapid_engine/imcs/chunk.cpp
storage/rapid_engine/imcs/chunk.h
storage/rapid_engine/imcs/cu.cpp
storage/rapid_engine/imcs/cu.h
storage/rapid_engine/imcs/imcs.cpp
storage/rapid_engine/include/rapid_const.h
storage/rapid_engine/include/rapid_context.h

to support text/string field encoding.

feat(rapid): add compression alg for string field

---

storage/rapid_engine/CMakeLists.txt
storage/rapid_engine/compress/algorithms.cpp
storage/rapid_engine/compress/algorithms.h
storage/rapid_engine/compress/dictionary/dictionary.cpp
storage/rapid_engine/compress/dictionary/dictionary.h
storage/rapid_engine/handler/ha_shannon_rapid.cc
storage/rapid_engine/handler/ha_shannon_rapid.h
storage/rapid_engine/imcs/chunk.cpp
storage/rapid_engine/imcs/chunk.h
storage/rapid_engine/imcs/cu.cpp
storage/rapid_engine/imcs/cu.h
storage/rapid_engine/imcs/imcs.cpp
storage/rapid_engine/imcs/imcs.h
storage/rapid_engine/imcs/imcu.cpp
storage/rapid_engine/imcs/imcu.h
storage/rapid_engine/iterators/iterator.cpp
storage/rapid_engine/iterators/iterator.h
storage/rapid_engine/reader/csv_reader.cpp
storage/rapid_engine/reader/csv_reader.h
storage/rapid_engine/reader/imcs_reader.cpp
storage/rapid_engine/reader/imcs_reader.h
storage/rapid_engine/reader/parquet_reader.cpp
storage/rapid_engine/reader/parquet_reader.h
storage/rapid_engine/reader/reader.h
storage/rapid_engine/trx/transaction.h

add imcs reader to read imcs, using reader to visit all data in imcs, not read directly.

feat(rapid): adds imcs reader

---

storage/rapid_engine/compress/algorithms.cpp
storage/rapid_engine/compress/algorithms.h
storage/rapid_engine/compress/dictionary/dictionary.cpp
storage/rapid_engine/handler/ha_shannon_rapid.cc
storage/rapid_engine/handler/ha_shannon_rapid.h
storage/rapid_engine/imcs/chunk.cpp
storage/rapid_engine/imcs/chunk.h
storage/rapid_engine/imcs/cu.cpp
storage/rapid_engine/imcs/cu.h
storage/rapid_engine/imcs/imcs.cpp
storage/rapid_engine/imcs/imcs.h
storage/rapid_engine/include/rapid_const.h
storage/rapid_engine/reader/csv_reader.cpp
storage/rapid_engine/reader/csv_reader.h
storage/rapid_engine/reader/imcs_reader.cpp
storage/rapid_engine/reader/imcs_reader.h
storage/rapid_engine/reader/parquet_reader.cpp
storage/rapid_engine/reader/parquet_reader.h
storage/rapid_engine/reader/reader.h

1: optimize read to reduce `__memset_avx2_unaligned_erms`
2: add `records_in_range`

feat(rapid): optimize read and adds records in range

---

storage/innobase/handler/ha_innodb.cc
storage/rapid_engine/compress/algorithms.cpp
storage/rapid_engine/compress/algorithms.h
storage/rapid_engine/compress/dictionary/dictionary.cpp
storage/rapid_engine/imcs/cu.cpp

1: refine the impl of compression algorithm.
2: fixup cannot get trxid in comb index.

feat(rapid): reinfe compression algo and `db_trx_id`

---

storage/rapid_engine/handler/ha_shannon_rapid.cc
storage/rapid_engine/imcs/imcs.cpp
storage/rapid_engine/include/rapid_const.h
storage/rapid_engine/reader/imcs_reader.cpp
storage/rapid_engine/reader/imcs_reader.h

reduce the memset calls on unalgined memory, which will consume to much system costs.

feat(rapid): reduce memset call on unaligned memory

---

storage/rapid_engine/imcs/chunk.cpp

fixup the way of getting the data in `Chunk::write_data_direct`.

fix(rapid): fixup meta info update

---

sql/handler.h
storage/rapid_engine/handler/ha_shannon_rapid.cc
storage/rapid_engine/handler/ha_shannon_rapid.h
storage/rapid_engine/imcs/chunk.cpp
storage/rapid_engine/imcs/chunk.h
storage/rapid_engine/imcs/cu.cpp
storage/rapid_engine/imcs/imcs.cpp
storage/rapid_engine/include/rapid_const.h
storage/rapid_engine/include/rapid_context.h
storage/rapid_engine/reader/csv_reader.cpp
storage/rapid_engine/reader/csv_reader.h
storage/rapid_engine/reader/imcs_reader.cpp
storage/rapid_engine/reader/imcs_reader.h
storage/rapid_engine/reader/parquet_reader.cpp
storage/rapid_engine/reader/parquet_reader.h
storage/rapid_engine/reader/reader.h
storage/rapid_engine/utils/utils.cpp
storage/rapid_engine/utils/utils.h

1: add index part ii;
2: enable icp(index condition pushdown)

feat(rapid):support index and enable icp

---

storage/rapid_engine/handler/ha_shannon_rapid.cc
storage/rapid_engine/include/rapid_const.h
storage/rapid_engine/utils/utils.cpp

fix the row count estimation in records_in_range.

fix(rapid):fix rows count in range

---

storage/rapid_engine/compress/dictionary/dictionary.cpp
storage/rapid_engine/compress/dictionary/dictionary.h
storage/rapid_engine/handler/ha_shannon_rapid.cc
storage/rapid_engine/handler/ha_shannon_rapid.h
storage/rapid_engine/imcs/imcs.cpp
storage/rapid_engine/include/rapid_const.h
storage/rapid_engine/include/rapid_context.h
storage/rapid_engine/reader/imcs_reader.cpp
storage/rapid_engine/utils/utils.cpp
storage/rapid_engine/utils/utils.h

1: refine index support.
2: enable index on `string` type.
3: enable supported type check.

fix(rapid): refine index support

---

storage/perfschema/pfs_engine_table.cc
storage/perfschema/table_rpd_preload_stats.cc
storage/perfschema/table_rpd_preload_stats.h
storage/perfschema/table_rpd_table_id.cc
storage/perfschema/table_rpd_tables.cc
storage/perfschema/table_rpd_tables.h
storage/rapid_engine/handler/ha_shannon_rapid.cc
storage/rapid_engine/handler/ha_shannon_rapid.h
storage/rapid_engine/include/rapid_stats.h

add meta tables.
1: PERFORMANCE_SCHEMA.rpd_preload_stats
2: PERFORMANCE_SCHEMA.rpd_table_id
3: PERFORMANCE_SCHEMA.rpd_tables

feat(rapid): add meta tables

---

storage/rapid_engine/handler/ha_shannon_rapid.cc
storage/rapid_engine/handler/ha_shannon_rapid.h
storage/rapid_engine/imcs/chunk.cpp
storage/rapid_engine/imcs/chunk.h
storage/rapid_engine/imcs/cu.cpp
storage/rapid_engine/imcs/cu.h
storage/rapid_engine/imcs/index/art.h
storage/rapid_engine/include/rapid_const.h
storage/rapid_engine/reader/csv_reader.cpp
storage/rapid_engine/reader/csv_reader.h
storage/rapid_engine/reader/imcs_reader.cpp
storage/rapid_engine/reader/imcs_reader.h
storage/rapid_engine/reader/parquet_reader.cpp
storage/rapid_engine/reader/parquet_reader.h
storage/rapid_engine/reader/reader.h
storage/rapid_engine/utils/utils.cpp

reimpl index of rapid using imcs. (it's temp approach)

fix(rapid): refine index impl

---

storage/rapid_engine/CMakeLists.txt
storage/rapid_engine/handler/ha_shannon_rapid.cc
storage/rapid_engine/handler/ha_shannon_rapid.h
storage/rapid_engine/imcs/chunk.cpp
storage/rapid_engine/imcs/cu.cpp
storage/rapid_engine/imcs/cu.h
storage/rapid_engine/imcs/imcs.cpp
storage/rapid_engine/imcs/index/art.cpp
storage/rapid_engine/imcs/index/art.h
storage/rapid_engine/imcs/index/index.cpp
storage/rapid_engine/imcs/index/index.h
storage/rapid_engine/include/rapid_context.h
storage/rapid_engine/reader/imcs_reader.cpp
storage/rapid_engine/reader/imcs_reader.h
storage/rapid_engine/reader/parquet_reader.cpp
storage/rapid_engine/reader/parquet_reader.h
storage/rapid_engine/reader/reader.h
storage/rapid_engine/utils/utils.cpp
storage/rapid_engine/utils/utils.h

to support ART index in rapid engine.

Index art used

---

storage/rapid_engine/handler/ha_shannon_rapid.cc
storage/rapid_engine/handler/ha_shannon_rapid.h
storage/rapid_engine/imcs/index/art.cpp
storage/rapid_engine/imcs/index/art.h
storage/rapid_engine/imcs/index/index.cpp
storage/rapid_engine/reader/imcs_reader.cpp

re-impl the cruise way of index scan.

feat(rapid): refine index cruise

---

storage/rapid_engine/handler/ha_shannon_rapid.cc
storage/rapid_engine/handler/ha_shannon_rapid.h
storage/rapid_engine/imcs/imcs.cpp
storage/rapid_engine/include/rapid_context.h
storage/rapid_engine/reader/csv_reader.cpp
storage/rapid_engine/reader/csv_reader.h
storage/rapid_engine/reader/imcs_reader.cpp
storage/rapid_engine/reader/imcs_reader.h
storage/rapid_engine/reader/parquet_reader.cpp
storage/rapid_engine/reader/parquet_reader.h
storage/rapid_engine/reader/reader.h

support composite index in rapid using ART.

feat(rapid): composite index support

---

storage/rapid_engine/handler/ha_shannon_rapid.cc
storage/rapid_engine/reader/csv_reader.cpp
storage/rapid_engine/reader/csv_reader.h
storage/rapid_engine/reader/imcs_reader.cpp
storage/rapid_engine/reader/imcs_reader.h
storage/rapid_engine/reader/parquet_reader.cpp
storage/rapid_engine/reader/parquet_reader.h
storage/rapid_engine/reader/reader.h

fixup ART index read only get the first rows in xxx-join loop.

fix(rapid):fixup index read

---

storage/rapid_engine/imcs/index/art.cpp
storage/rapid_engine/imcs/index/art.h
storage/rapid_engine/imcs/index/index.cpp
storage/rapid_engine/imcs/index/index.h
storage/rapid_engine/reader/imcs_reader.cpp
storage/rapid_engine/reader/imcs_reader.h

to enable fast-ART index crusie.

feat(rapid): fast-ART-index cruise

---

storage/rapid_engine/handler/ha_shannon_rapid.cc
storage/rapid_engine/imcs/chunk.cpp
storage/rapid_engine/imcs/cu.cpp
storage/rapid_engine/imcs/imcs.cpp
storage/rapid_engine/imcs/index/art.cpp
storage/rapid_engine/imcs/index/art.h
storage/rapid_engine/imcs/index/index.cpp
storage/rapid_engine/imcs/index/index.h
storage/rapid_engine/include/rapid_arch_inf.h
storage/rapid_engine/reader/imcs_reader.cpp
storage/rapid_engine/reader/imcs_reader.h
storage/rapid_engine/utils/utils.cpp
storage/rapid_engine/utils/utils.h

reimpl the ICP in rapid, to support index condition push down in rapid engine.

feat(rapid): fixup ART index

---

ml/auto_ml.cpp
ml/ml_anomaly_detection.cpp
ml/ml_anomaly_detection.h
ml/ml_forecasting.cpp
ml/ml_forecasting.h
ml/ml_recommendation.cpp
ml/ml_recommendation.h
ml/ml_regression.cpp
ml/ml_regression.h
sql/CMakeLists.txt

feat(shannonbase): Auto ML framework

---

ml/auto_ml.cpp
ml/ml_regression.cpp
ml/ml_regression.h
sql/item_func.cc
storage/rapid_engine/handler/ha_shannon_rapid.cc

when the model trained, write the meta data into ML_SCHEMA_'user_name'.MODEL_CATALOG.

feat(shannon): write the meat to MODEL_CATALOG tale

---

scripts/sys_schema/procedures/ml_train.sql

make the column of 'model_handle' to be unique.

feat(shannonbase): change MODEL_CATALOG table definition

---

ml/auto_ml.cpp
ml/auto_ml.h
ml/ml_algorithm.h
ml/ml_anomaly_detection.cpp
ml/ml_anomaly_detection.h
ml/ml_classification.cpp
ml/ml_classification.h
ml/ml_forecasting.h
ml/ml_recommendation.cpp
ml/ml_recommendation.h
ml/ml_regression.cpp
ml/ml_regression.h
ml/ml_utils.cpp
ml/ml_utils.h
scripts/sys_schema/procedures/ml_model_load.sql
scripts/sys_schema/procedures/ml_train.sql
sql/CMakeLists.txt
sql/item_create.cc
sql/item_func.cc

to enable `ml_model_load` and refine `ml_train`.

feat(shannon):to enable ml_model_load

---

storage/innobase/log/log0buf.cc
storage/rapid_engine/imcs/chunk.cpp
storage/rapid_engine/imcs/chunk.h
storage/rapid_engine/imcs/cu.cpp
storage/rapid_engine/imcs/cu.h
storage/rapid_engine/imcs/imcs.cpp
storage/rapid_engine/populate/log_parser.cpp
storage/rapid_engine/populate/log_parser.h
storage/rapid_engine/reader/imcs_reader.cpp
storage/rapid_engine/utils/utils.cpp

fixup bugs of changes pop to rapid.

fix(shannon): fixup changes pop to rapid

---

storage/innobase/log/log0buf.cc
storage/rapid_engine/populate/log_parser.cpp

adjust the redo log parsing types.

feat(shannon): refine redo parsing.

---

sql/sql_table.cc
storage/rapid_engine/populate/log_parser.cpp
storage/rapid_engine/populate/populate.cpp

refine log parsing and release the mdl ticket

Refine rapid log parse

---

sql/sql_table.cc
storage/innobase/log/log0buf.cc
storage/rapid_engine/imcs/chunk.cpp
storage/rapid_engine/imcs/chunk.h
storage/rapid_engine/imcs/cu.cpp
storage/rapid_engine/imcs/cu.h
storage/rapid_engine/imcs/imcs.cpp
storage/rapid_engine/populate/log_parser.cpp
storage/rapid_engine/populate/log_parser.h
storage/rapid_engine/populate/populate.cpp
storage/rapid_engine/reader/imcs_reader.cpp
storage/rapid_engine/utils/utils.cpp

parses the changes in innodb and pops to rapid

parse the changes and pop to rapid

---

mysql-test/suite/secondary_engine/r/shannon_change_pop.result
mysql-test/suite/secondary_engine/t/shannon_change_pop.test
sql/handler.h
storage/innobase/handler/ha_innodb.cc
storage/innobase/handler/ha_innodb.h
storage/rapid_engine/handler/ha_shannon_rapid.cc
storage/rapid_engine/handler/ha_shannon_rapid.h

refine the logic of trx in rapid and mtr for concurrency.

feat(shannon): refine handling of trx in rapid

---

mysql-test/suite/secondary_engine/r/shannon_change_pop.result
mysql-test/suite/secondary_engine/t/shannon_change_pop.test

for maunnual trx concurrency in rapid.

mtr(shannon): for concurrency in rapid

---

sql/CMakeLists.txt
sql/vector/bitvector.cpp
sql/vector/bitvector.h
sql/vector/halfutils.cpp
sql/vector/halfutils.h
sql/vector/halfvec.h
sql/vector/vector.cpp
sql/vector/vector.h
sql/vector/vector_comm.cpp
sql/vector/vector_comm.h

part of supporting vector data type.

feat(shannon): for vector type

---

ml/auto_ml.cpp
ml/auto_ml.h
ml/ml_algorithm.h
ml/ml_anomaly_detection.cpp
ml/ml_anomaly_detection.h
ml/ml_classification.cpp
ml/ml_classification.h
ml/ml_forecasting.cpp
ml/ml_forecasting.h
ml/ml_recommendation.cpp
ml/ml_recommendation.h
ml/ml_regression.cpp
ml/ml_regression.h
scripts/sys_schema/procedures/ml_model_load.sql
sql/item_func.cc
storage/rapid_engine/populate/log_parser.cpp
storage/rapid_engine/populate/log_parser.h

fix(shannon): refine and fix ML functions

---

.github/workflows/pull-requests.yaml
ml/ml_regression.cpp

action(shannon): add mtr actions

---

.github/workflows/pull-requests.yaml

- Fixes #29 
- [ x] No Test  - _Explain why_
- [x ] Other (please describe):

fix(action): hot fix git action

---

storage/innobase/log/log0buf.cc
storage/innobase/mtr/mtr0mtr.cc
storage/rapid_engine/populate/log_parser.cpp
storage/rapid_engine/populate/log_parser.h
storage/rapid_engine/populate/populate.cpp

to avoid copying the holes to pop buffer.

fix(shannon):fixup the cpy the hole of log buffer into pop buff

---

storage/innobase/handler/ha_innodb.cc
storage/rapid_engine/populate/log_parser.cpp
storage/rapid_engine/populate/log_parser.h
storage/rapid_engine/populate/populate.cpp

_Refine the impl of mlog parser._

Refine mlog parser rapid

---

.github/workflows/pull-requests.yaml
mysql-test/r/mysqld--help-notwin.result
storage/innobase/handler/ha_innodb.cc
storage/rapid_engine/include/rapid_arch_inf.h
storage/rapid_engine/populate/log_parser.cpp

hotfix(rapid): hotfix compiling err in release

---

mysql-test/suite/secondary_engine/t/shannon_case1.test
storage/innobase/mtr/mtr0mtr.cc
storage/rapid_engine/compress/algorithms.cpp
storage/rapid_engine/compress/algorithms.h
storage/rapid_engine/compress/dictionary/dictionary.cpp
storage/rapid_engine/include/rapid_const.h
storage/rapid_engine/populate/log_parser.cpp
storage/rapid_engine/populate/log_parser.h
storage/rapid_engine/reader/imcs_reader.cpp

_to improve performance of rapid._

feat(shannon):impr the perfomrance of rapid

---

.github/workflows/pull-requests.yaml

_more mtrs and git actions._
- Fixes #185

action(shannon): mtrs and git actions

---

.github/workflows/nightly.yaml
mysql-test/collections/disabled.def
storage/rapid_engine/handler/ha_shannon_rapid.cc
storage/rapid_engine/handler/ha_shannon_rapid.h

_mtrs and git actions._
- Fixes #185

action(shannon): mtrs and actions

---

.github/workflows/nightly.yaml
.github/workflows/pull-requests.yaml
ml/ml_regression.cpp
mysql-test/collections/disabled.def
storage/innobase/handler/ha_innodb.cc
storage/innobase/row/row0ins.cc
storage/perfschema/table_rpd_table_id.cc
storage/rapid_engine/handler/ha_shannon_rapid.cc
storage/rapid_engine/handler/ha_shannon_rapid.h
storage/rapid_engine/imcs/imcs.cpp
storage/rapid_engine/populate/log_parser.cpp
storage/rapid_engine/populate/populate.cpp

mereg develop to main

---

sql/handler.h
sql/pq_range.h
storage/innobase/handler/ha_innodb.h
storage/innobase/handler/handler0alter.cc
storage/innobase/include/btr0pcur.h
storage/innobase/include/data0data.h
storage/innobase/include/db0err.h
storage/innobase/include/read0read.h
storage/innobase/include/read0types.h
storage/innobase/include/rem0cmp.h
storage/innobase/include/row0mysql.h
storage/innobase/include/row0pread.h
storage/innobase/include/row0sel.h
storage/innobase/include/srv0srv.h
storage/innobase/include/trx0trx.h
storage/innobase/read/read0read.cc
storage/innobase/rem/rem0cmp.cc
storage/innobase/row/row0pread.cc
storage/innobase/row/row0sel.cc
storage/innobase/srv/srv0srv.cc
storage/innobase/trx/trx0trx.cc
storage/innobase/ut/ut0ut.cc

_the base funcs for parallel scanning.._
- Fixes #28

feat(shannon):base funcs for parallel scan

---

.github/workflows/weekly.yaml

action(shannon):git weekly action

---

mysql-test/r/mysqld--help-notwin.result
sql/field.cc
sql/field.h
sql/item.cc
sql/item.h
sql/item_func.cc
sql/item_strfunc.h
sql/item_sum.cc
sql/item_sum.h
sql/item_timefunc.h
sql/mysqld.cc
sql/mysqld.h
sql/query_result.cc
sql/sql_class.h
sql/sql_lex.cc
sql/sql_lex.h
sql/sql_parallel.h
sql/sql_pq_condition.cc
sql/sql_pq_condition.h
sql/sql_prepare.cc
sql/sql_resolver.cc
sql/sql_tmp_table.cc
sql/sys_vars.cc

_part ii of parallel query processing.._
- Fixes #28

feat(shannon): parallel query processing ii

---

.github/workflows/nightly.yaml
.github/workflows/pull-requests.yaml
.github/workflows/weekly.yaml

action(flow): revise the git action

---

.github/workflows/pull-requests.yaml

action(flow):print runner info

---

.github/workflows/nightly.yaml
.github/workflows/pull-requests.yaml
storage/federated/ha_federated.cc

_fix up for federate engine in mtr.federate.xxx._

fix(shannon):fixup mtr for federate storage

---

ml/readme.txt

doc(shannon): update ml readme

---

.github/workflows/nightly.yaml
.github/workflows/pull-requests.yaml
.github/workflows/weekly.yaml

feat(flow): enable hyper-graph-compile

---

.github/workflows/nightly.yaml

fix(flow): hot fix nightly

---

.github/workflows/nightly.yaml

fix(flow): fix nightly flow

---

mysql-test/suite/secondary_engine/r/shannon_change_pop.result
mysql-test/suite/secondary_engine/t/shannon_change_pop.test

_chage pop mtr, will be added after fixed._

fix(test): change pop mtr

---

mysql-test/suite/secondary_engine/r/shannon_change_pop.result
mysql-test/suite/secondary_engine/t/shannon_change_pop.test
storage/rapid_engine/imcs/cu.cpp
storage/rapid_engine/imcs/cu.h
storage/rapid_engine/imcs/data_table.cpp
storage/rapid_engine/imcs/imcs.cpp
storage/rapid_engine/imcs/imcs.h
storage/rapid_engine/populate/log_parser.cpp
storage/rapid_engine/populate/populate.cpp

_fixup in delete all oper, which cannot deal with `delete from xxx` propoerly.._
- [] No Test  - _Explain why_

fix(shannon):fixup in delete oper

---

mysql-test/suite/secondary_engine/r/shannon_change_pop.result
mysql-test/suite/secondary_engine/t/shannon_change_pop.test
storage/rapid_engine/compress/dictionary/dictionary.cpp
storage/rapid_engine/compress/dictionary/dictionary.h
storage/rapid_engine/imcs/chunk.cpp
storage/rapid_engine/imcs/cu.cpp
storage/rapid_engine/imcs/data_table.cpp
storage/rapid_engine/imcs/imcs.cpp
storage/rapid_engine/populate/log_parser.cpp
storage/rapid_engine/populate/log_parser.h
storage/rapid_engine/populate/populate.cpp
storage/rapid_engine/utils/utils.cpp
storage/rapid_engine/utils/utils.h

_1: enable blob type.
2: minor changes.
3: mtr changes for utf-8._

feat(shannon): enable blob type and minor changes

---

storage/rapid_engine/imcs/imcs.cpp
storage/rapid_engine/populate/populate.cpp

_to fixup the operation of secondary unload hang.._

fix(shannon):unload table

---

mysql-test/suite/secondary_engine/r/shannon_case3.result
mysql-test/suite/secondary_engine/r/shannon_case4.result
mysql-test/suite/secondary_engine/t/shannon_case3.test
mysql-test/suite/secondary_engine/t/shannon_case4.test
storage/innobase/row/row0upd.cc
storage/rapid_engine/populate/log_parser.cpp
storage/rapid_engine/utils/utils.h

fix(shannon):to delete entire row

---

mysql-test/suite/secondary_engine/r/shannon_case6.result
mysql-test/suite/secondary_engine/t/shannon_case6.test
storage/rapid_engine/imcs/data_table.cpp

feat(shannon): fixup not secondary column

---

mysql-test/suite/secondary_engine/r/shannon_case6.result
mysql-test/suite/secondary_engine/t/shannon_case6.test
sql/sql_table.cc
storage/rapid_engine/imcs/imcs.cpp
storage/rapid_engine/populate/log_parser.cpp

_fixup in `not_secondary` column._

feat(shannon):fix  column

---

mysql-test/suite/secondary_engine/r/shannon_case6.result
mysql-test/suite/secondary_engine/t/shannon_case6.test
storage/rapid_engine/imcs/chunk.cpp
storage/rapid_engine/imcs/chunk.h
storage/rapid_engine/imcs/cu.cpp
storage/rapid_engine/imcs/imcs.cpp

_1: fixup in delete row and unload sync
2:add context for functions._

feat(shannon): fix-unload-rapid

---

mysql-test/suite/secondary_engine/r/shannon_case6.result
mysql-test/suite/secondary_engine/t/shannon_case6.test
sql/sql_table.cc
storage/rapid_engine/imcs/chunk.cpp
storage/rapid_engine/imcs/chunk.h
storage/rapid_engine/imcs/cu.cpp
storage/rapid_engine/imcs/data_table.cpp
storage/rapid_engine/imcs/imcs.cpp
storage/rapid_engine/populate/log_parser.cpp

merge develop to main

---

storage/innobase/row/row0sel.cc
storage/rapid_engine/handler/ha_shannon_rapid.cc
storage/rapid_engine/handler/ha_shannon_rapid.h
storage/rapid_engine/imcs/chunk.cpp
storage/rapid_engine/imcs/chunk.h
storage/rapid_engine/imcs/data_table.cpp
storage/rapid_engine/imcs/data_table.h
storage/rapid_engine/imcs/imcs.cpp
storage/rapid_engine/imcs/imcs.h
storage/rapid_engine/include/rapid_const.h
storage/rapid_engine/include/rapid_context.h
storage/rapid_engine/trx/transaction.cpp
storage/rapid_engine/trx/transaction.h

to impl transaction in rapid.
_To impl trx in rapid._

feat(shannon):impl trx in rapid engine

---

.github/workflows/nightly.yaml
mysql-test/suite/opt_trace/r/bugs_no_prot_all.result
mysql-test/suite/opt_trace/r/bugs_no_prot_none.result
mysql-test/suite/opt_trace/r/filesort_pq.result
mysql-test/suite/opt_trace/r/fulltext.result
mysql-test/suite/opt_trace/r/general2_no_prot.result
mysql-test/suite/opt_trace/r/general_no_prot_all.result
mysql-test/suite/opt_trace/r/general_no_prot_none.result
mysql-test/suite/opt_trace/r/range_no_prot.result
mysql-test/suite/opt_trace/r/subquery_no_prot.result
mysql-test/suite/perfschema/r/object_collation_lctn_1.result
mysql-test/suite/sys_vars/r/all_vars.result
mysql-test/suite/sys_vars/r/windowing_use_high_precision_basic.result
storage/rapid_engine/CMakeLists.txt
storage/rapid_engine/imcs/chunk.h
storage/rapid_engine/imcs/cu.h
storage/rapid_engine/include/rapid_arch_inf.h
storage/rapid_engine/include/rapid_const.h
storage/rapid_engine/utils/cache_line_size_amd.cpp
storage/rapid_engine/utils/cache_line_size_intel.cpp
storage/rapid_engine/utils/cpu_cache_size_amd.cpp
storage/rapid_engine/utils/cpu_cache_size_intel.cpp

_1:fixup results of mts.
2:to revies how to get cache line size and cache size.._

feat(mtr): fixup mtrs

---

storage/rapid_engine/compress/algorithms.cpp
storage/rapid_engine/compress/algorithms.h
storage/rapid_engine/compress/dictionary/dictionary.cpp
storage/rapid_engine/imcs/data_table.cpp

_to fix mis-using uncompressed string.._

fix(rapid): to fix using uncompressed text

---

storage/rapid_engine/compress/algorithms.cpp
storage/rapid_engine/compress/algorithms.h
storage/rapid_engine/imcs/data_table.cpp

_fix uncompress string in lz4 algo._

feat(rapid):fix uncompressing in lz4

---

mysql-test/suite/secondary_engine/r/explain.result
mysql-test/suite/secondary_engine/r/explain_hypergraph.result
mysql-test/suite/secondary_engine/r/plan_cost_debug.result
mysql-test/suite/secondary_engine/r/secondary_engine_bugs.result
mysql-test/suite/secondary_engine/r/shannon_case6.result
mysql-test/suite/secondary_engine/r/shannon_change_pop.result
mysql-test/suite/secondary_engine/r/shannon_change_pop_1.result
mysql-test/suite/secondary_engine/r/shannon_change_pop_2.result
mysql-test/suite/secondary_engine/r/transforms.result
mysql-test/suite/secondary_engine/r/transforms_hypergraph.result
sql/field.h
storage/rapid_engine/cost/cost.cpp
storage/rapid_engine/cost/cost.h
storage/rapid_engine/handler/ha_shannon_rapid.cc
storage/rapid_engine/handler/ha_shannon_rapid.h
storage/rapid_engine/imcs/chunk.cpp
storage/rapid_engine/imcs/cu.cpp
storage/rapid_engine/imcs/imcs.cpp
storage/rapid_engine/include/rapid_const.h

_1: cost model
2: refine # of records in rapid.._
- Fixes #181

feat(shannon): cost model

---

storage/rapid_engine/imcs/data_table.cpp

fix(shannon):adjust prefetch

---

sql/handler.h
sql/sql_base.cc
sql/sql_class.cc
sql/sql_class.h
sql/sql_cmd.h
sql/sql_cmd_ddl_table.cc
sql/sql_cmd_ddl_table.h
sql/sql_cmd_dml.h
sql/sql_do.h
sql/sql_insert.cc
sql/sql_insert.h
sql/sql_parse.cc
sql/sql_prepare.cc
sql/sql_select.cc
sql/sql_select.h
storage/innobase/include/ha_prototypes.h
storage/rapid_engine/handler/ha_shannon_rapid.cc

_selective dynamic offload._
- Fixes #275

feat(shannon): selective dynamic offload

---

mysql-test/r/variables.result
mysql-test/suite/secondary_engine/r/system_variables.result
mysql-test/suite/secondary_engine/t/system_variables.test
sql/sys_vars.cc
sql/system_variables.h
storage/rapid_engine/populate/populate.cpp
storage/rapid_engine/populate/populate.h

adding a system variable, `use_rapid_dynamic_offload`.
_adding a system var._

feat(shannon): add sys var use_rapid_dynamic_offload

---

mysql-test/r/variables.result
mysql-test/suite/secondary_engine/r/optimizer_trace.result
mysql-test/suite/secondary_engine/r/system_variables.result
mysql-test/suite/secondary_engine/t/system_variables.test
sql/sp_instr.cc
sql/sql_base.cc
sql/sql_class.h
sql/sys_vars.cc
sql/system_variables.h
storage/rapid_engine/handler/ha_shannon_rapid.cc
storage/rapid_engine/include/rapid_context.h
storage/rapid_engine/populate/populate.cpp
storage/rapid_engine/populate/populate.h

_to support dynamic offload var._
- Fixes a part of #275

Dynamic offload var

---

mysql-test/suite/secondary_engine/inc/secondary_engine_bugs.inc
mysql-test/suite/secondary_engine/r/query_preparation.result
mysql-test/suite/secondary_engine/r/secondary_engine_bugs.result
mysql-test/suite/secondary_engine/r/secondary_engine_bugs_hypergraph.result
mysql-test/suite/secondary_engine/r/shannon_case3.result
mysql-test/suite/secondary_engine/r/shannon_case6.result
mysql-test/suite/secondary_engine/r/shannon_tpch.result
mysql-test/suite/secondary_engine/t/query_preparation.test
mysql-test/suite/secondary_engine/t/shannon_case3.test
mysql-test/suite/secondary_engine/t/shannon_case6.test
mysql-test/suite/secondary_engine/t/shannon_tpch.test
sql/join_optimizer/join_optimizer.cc
sql/sql_class.cc
sql/sql_class.h
sql/sql_lex.h
storage/rapid_engine/handler/ha_shannon_rapid.cc
storage/rapid_engine/handler/ha_shannon_rapid.h
storage/rapid_engine/populate/populate.cpp
storage/rapid_engine/populate/populate.h

feat(shannon): dynamic offload impl

---

mysql-test/suite/secondary_engine/t/shannon_tpch.test
sql/sql_class.cc
sql/sql_class.h
storage/rapid_engine/handler/ha_shannon_rapid.cc
storage/rapid_engine/populate/populate.cpp
storage/rapid_engine/populate/populate.h

_selective offload, to refresh the cached plan info._
- Fixes a part of #275

feat(shannon): selective offload

---

sql/join_optimizer/finalize_plan.cc
sql/join_optimizer/finalize_plan.h
sql/sql_class.cc
sql/sql_class.h
storage/rapid_engine/CMakeLists.txt
storage/rapid_engine/handler/ha_shannon_rapid.cc
storage/rapid_engine/ml/ml.cpp
storage/rapid_engine/ml/ml.h
storage/rapid_engine/utils/utils.cpp
storage/rapid_engine/utils/utils.h

_selective offload cost-based offload model._
- Fixes a part of #275

feat(shannon):selective offload, offload-model

---

mysql-test/suite/secondary_engine/r/optimizer_trace.result
mysql-test/suite/secondary_engine/t/shannon_tpch.test
storage/rapid_engine/handler/ha_shannon_rapid.cc
storage/rapid_engine/utils/utils.cpp
storage/rapid_engine/utils/utils.h

_refine offload._
- Fixes a part of #275

feat(shannon): refine selective-offload

---

storage/rapid_engine/ml/ml.cpp
storage/rapid_engine/ml/ml.h
storage/rapid_engine/utils/utils.cpp

_this is different to SelectExecutedIn in handler.h._

feat(shannon): changes class indicator

---

.github/workflows/nightly.yaml
.github/workflows/pull-requests.yaml
.github/workflows/weekly.yaml

feat(workflow): fix boost download url

---

storage/rapid_engine/imcs/chunk.cpp
storage/rapid_engine/imcs/chunk.h
storage/rapid_engine/imcs/cu.cpp
storage/rapid_engine/imcs/cu.h
storage/rapid_engine/trx/transaction.h

feat(shannon):refine header files

---

mysql-test/suite/secondary_engine/r/query_preparation.result

test(mtr): fix mtr result

---

storage/rapid_engine/imcs/imcs.h
storage/rapid_engine/optimizer/optimizer.cpp
storage/rapid_engine/populate/log_commons.h
storage/rapid_engine/populate/populate.cpp
storage/rapid_engine/populate/populate.h

_refine performance of rapid._

feat(shannon):refine pop thread perfomrance

---

storage/rapid_engine/handler/ha_shannon_rapid.cc
storage/rapid_engine/imcs/chunk.cpp
storage/rapid_engine/imcs/data_table.cpp
storage/rapid_engine/populate/populate.cpp

feat(shannon):rpd status added

---

storage/rapid_engine/handler/ha_shannon_rapid.cc
storage/rapid_engine/imcs/chunk.cpp
storage/rapid_engine/imcs/chunk.h
storage/rapid_engine/imcs/cu.cpp
storage/rapid_engine/imcs/data_table.cpp
storage/rapid_engine/include/rapid_context.h

feat(shannon):refine-rapid-impl

---

storage/rapid_engine/CMakeLists.txt

feat(rapid): fix unreslove functions

---

storage/innobase/fsp/fsp0fsp.cc
storage/innobase/include/mtr0mtr.ic
storage/innobase/include/mtr0types.h
storage/innobase/mtr/mtr0mtr.cc
storage/rapid_engine/compress/algorithms.cpp
storage/rapid_engine/compress/dictionary/dictionary.cpp
storage/rapid_engine/populate/populate.cpp

feat(shannon): min fix up

---

mysql-test/r/initialize.result
mysql-test/r/ps_sys_upgrade.result

test(mtr): hot fix mtr results

---

.github/workflows/nightly.yaml
.github/workflows/pull-requests.yaml
.github/workflows/weekly.yaml
ml/auto_ml.cpp
ml/auto_ml.h
ml/ml_algorithm.h
ml/ml_anomaly_detection.cpp
ml/ml_anomaly_detection.h
ml/ml_classification.cpp
ml/ml_classification.h
ml/ml_forecasting.cpp
ml/ml_forecasting.h
ml/ml_recommendation.cpp
ml/ml_recommendation.h
ml/ml_regression.cpp
ml/ml_regression.h
ml/ml_utils.cpp
ml/ml_utils.h
sql/item_func.cc

feat(shannon): impl ml algorithms

---

ml/auto_ml.cpp
ml/auto_ml.h
ml/ml_algorithm.h
ml/ml_anomaly_detection.cpp
ml/ml_anomaly_detection.h
ml/ml_classification.cpp
ml/ml_classification.h
ml/ml_forecasting.cpp
ml/ml_forecasting.h
ml/ml_recommendation.cpp
ml/ml_recommendation.h
ml/ml_regression.cpp
ml/ml_regression.h
ml/ml_utils.cpp
ml/ml_utils.h
scripts/sys_schema/procedures/ml_explain.sql
scripts/sys_schema/procedures/ml_model_import.sql
scripts/sys_schema/procedures/ml_score.sql
sql/item_create.cc
sql/item_func.cc

feat(shannon): impl ml algo v

---

mysql-test/r/initialize.result
mysql-test/r/ps_sys_upgrade.result

feat(mtr):hot fix mtr results

---

ml/ml_classification.cpp

feat(shannon): imp ml alg viiii

---

ml/auto_ml.cpp
ml/ml_classification.cpp
ml/ml_classification.h
ml/ml_utils.cpp
ml/ml_utils.h

merge develop into main

---

ml/auto_ml.cpp
ml/ml_algorithm.h
ml/ml_anomaly_detection.cpp
ml/ml_anomaly_detection.h
ml/ml_classification.cpp
ml/ml_classification.h
ml/ml_forecasting.cpp
ml/ml_forecasting.h
ml/ml_info.h
ml/ml_recommendation.cpp
ml/ml_recommendation.h
ml/ml_regression.cpp
ml/ml_regression.h
ml/ml_utils.cpp
ml/ml_utils.h
ml/readme.txt
mysql-test/suite/ml/r/ml_score.result
scripts/sys_schema/procedures/ml_train.sql
sql/item_func.cc

feat(shannon): impl ml algo vvi

---

ml/ml_anomaly_detection.cpp
ml/ml_anomaly_detection.h
ml/ml_classification.cpp
ml/ml_forecasting.cpp
ml/ml_info.h
ml/ml_recommendation.cpp
ml/ml_regression.cpp
ml/ml_utils.cpp
ml/ml_utils.h

feat(shanon): impl ml algo vviii

---

ml/ml_anomaly_detection.cpp
ml/ml_classification.cpp
ml/ml_classification.h
ml/ml_forecasting.cpp
ml/ml_recommendation.cpp
ml/ml_regression.cpp
ml/ml_utils.cpp

_fix up compilation error in release mode._

feat(shannon):changes fix for release ver

---

storage/rapid_engine/handler/ha_shannon_rapid.cc
storage/rapid_engine/imcs/chunk.cpp
storage/rapid_engine/imcs/chunk.h
storage/rapid_engine/imcs/cu.cpp
storage/rapid_engine/imcs/cu.h
storage/rapid_engine/imcs/data_table.cpp
storage/rapid_engine/imcs/imcs.cpp
storage/rapid_engine/imcs/imcs.h
storage/rapid_engine/include/rapid_const.h
storage/rapid_engine/trx/readview.cpp
storage/rapid_engine/trx/readview.h
storage/rapid_engine/trx/transaction.cpp
storage/rapid_engine/trx/transaction.h

refine the impl of imcs module, such as chunk, cu, etc.
_optimize imcs impl._

feat(shannon): optimize imcs impl

---

mysql-test/suite/sysschema/r/all_sys_objects_exist.result

_fix a MTR result._
- [] Unit Test

feat(mtr):fix mtr result

---

mysql-test/suite/secondary_engine/r/shannon_case6.result
mysql-test/suite/secondary_engine/t/shannon_case6.test
storage/rapid_engine/handler/ha_shannon_rapid.cc
storage/rapid_engine/imcs/data_table.cpp
storage/rapid_engine/imcs/imcs.cpp
storage/rapid_engine/imcs/imcs.h
storage/rapid_engine/include/rapid_const.h
storage/rapid_engine/include/rapid_context.h
storage/rapid_engine/populate/log_parser.cpp
storage/rapid_engine/populate/populate.cpp
storage/rapid_engine/trx/readview.cpp

_fix assertion failed in find matched rows._

feat(shannon): fix assertion failed in find matched rows

---

README.md

feat(reame): add badages for workfloww

---

sql/join_optimizer/finalize_plan.cc
sql/join_optimizer/finalize_plan.h
storage/rapid_engine/handler/ha_shannon_rapid.cc
storage/rapid_engine/ml/ml.cpp
storage/rapid_engine/ml/ml.h
storage/rapid_engine/utils/utils.cpp
storage/rapid_engine/utils/utils.h

_to refine point_select condition._

feat(shannon): to refine point_select condition

---

README.md

feat(readme): to update README.md

---

extra/jerryscript/CMakeLists.txt
extra/jerryscript/jerry-core/CMakeLists.txt
extra/jerryscript/jerry-ext/CMakeLists.txt
extra/jerryscript/jerry-main/CMakeLists.txt
extra/jerryscript/jerry-port/CMakeLists.txt

_upgrade the min cmake version to 3.5 on the latest git action runner._

fix(jerry):to upgrade min version in jerryscript cmake

---

storage/innobase/handler/ha_innodb.cc
storage/rapid_engine/imcs/chunk.cpp
storage/rapid_engine/imcs/chunk.h
storage/rapid_engine/imcs/data_table.cpp
storage/rapid_engine/imcs/imcs.cpp
storage/rapid_engine/imcs/imcs.h
storage/rapid_engine/imcs/purge/purge.cpp
storage/rapid_engine/include/rapid_const.h
storage/rapid_engine/trx/readview.cpp
storage/rapid_engine/trx/readview.h

_re-impl rollback in imcs and bugs fix in purge._

fix(rapid):fix bugs in version build and purge

---

storage/rapid_engine/imcs/data_table.cpp
storage/rapid_engine/trx/readview.cpp
storage/rapid_engine/trx/readview.h

Fix rollback visibility

---

sql/CMakeLists.txt

_hot fix cmake including dirs._

feat(cmake):fix include dir

---

ml/auto_ml.cpp
ml/auto_ml.h
mysql-test/r/mysqldump.result
scripts/sys_schema/CMakeLists.txt
scripts/sys_schema/procedures/ml_model_active.sql
scripts/sys_schema/procedures/ml_model_export.sql
scripts/sys_schema/procedures/ml_predict_row.sql
sql/CMakeLists.txt
sql/item_create.cc
sql/item_func.cc
sql/item_func.h

_to support ml_model_active, ml_predict_row, etc functions._
- Fixes #345

feat(ml):to enable more ml_xxx functions

---

.gitmodules

feat(submodel): add jemalloc submodel

---

scripts/sys_schema/procedures/ml_model_export.sql

_more ml_xxx functions._
- Fixes #345

feat(shannon):more ml_xxx functions supported

---

mysql-test/suite/secondary_engine/t/shannon_case6.test
storage/rapid_engine/include/rapid_context.h
storage/rapid_engine/populate/log_parser.cpp
storage/rapid_engine/populate/log_parser.h
storage/rapid_engine/populate/populate.cpp

_Optimize log parser thread to accelerate getting names._

feat(rapid):optimize log parser

---

mysql-test/r/initialize.result
mysql-test/r/ps_sys_upgrade.result
mysql-test/suite/sysschema/r/all_sys_objects_exist.result

feat(mtr): fix up mtr results

---

README.md
storage/rapid_engine/imcs/imcs.cpp
storage/rapid_engine/imcs/imcs.h
storage/rapid_engine/include/rapid_object.h
storage/rapid_engine/populate/log_parser.cpp
storage/rapid_engine/populate/log_parser.h
storage/rapid_engine/populate/populate.cpp

_to enable thread pool for co-routine._
- Fixes #420

feat(shannon): to enable thread pool for co-routine

---

mysql-test/suite/secondary_engine/r/shannon_case6.result
mysql-test/suite/secondary_engine/t/shannon_case6.test
storage/rapid_engine/handler/ha_shannon_rapid.cc
storage/rapid_engine/imcs/chunk.cpp
storage/rapid_engine/imcs/chunk.h
storage/rapid_engine/imcs/cu.cpp
storage/rapid_engine/imcs/cu.h
storage/rapid_engine/imcs/data_table.h
storage/rapid_engine/imcs/imcs.cpp
storage/rapid_engine/imcs/index/iterator.h
storage/rapid_engine/include/rapid_status.h
storage/rapid_engine/populate/log_parser.cpp

_refine memory management usage._

feat(rapid): to fixup memory usage management

---

storage/rapid_engine/CMakeLists.txt
storage/rapid_engine/reader/csv_reader.cpp
storage/rapid_engine/reader/csv_reader.h
storage/rapid_engine/reader/parquet_reader.cpp
storage/rapid_engine/reader/parquet_reader.h
storage/rapid_engine/reader/reader.h

to impl the readers, such as csv reader, parquet file reader, etc.
_ to impl the readers._
- Fixes #31 
- [] Performance Improvement

feat(rapid): to impl the readers

---

CMakeLists.txt
storage/rapid_engine/CMakeLists.txt
storage/rapid_engine/imcs/chunk.cpp
storage/rapid_engine/imcs/chunk.h
storage/rapid_engine/utils/utils.h

_refine cmake option for with_lakehouse._

feat(cmake): to refine with_lakehouse cmake option

---

cmake/FindONNXRuntime.cmake
mysql-test/suite/secondary_engine/t/shannon_case3.test
mysql-test/suite/secondary_engine/t/shannon_case6.test
mysql-test/suite/secondary_engine/t/shannon_change_pop.test
mysql-test/suite/secondary_engine/t/shannon_change_pop_2.test
mysql-test/suite/secondary_engine/t/shannon_index.test
storage/rapid_engine/imcs/cu.cpp
storage/rapid_engine/imcs/cu.h
storage/rapid_engine/populate/log_parser.cpp
storage/rapid_engine/populate/log_parser.h

_1: to reduce memory allocation/free oper.
2: re-construct the redundent code.._

feat(rapid): to tune the performance

---

storage/rapid_engine/include/rapid_const.h
storage/rapid_engine/populate/log_parser.cpp
storage/rapid_engine/populate/log_parser.h
storage/rapid_engine/utils/concurrent.h
storage/rapid_engine/utils/cpu.h
storage/rapid_engine/utils/utils.h

_1: using the corountine for reading
2: using adaptive batch size for log parsing, the size adjusts according to cpu usage.._

feat(rapid):for performance tuning

---

README.md

feat(readme):to update readme

---

.github/workflows/nightly.yaml
.github/workflows/weekly.yaml

feat(workflow): add arm workflow

---

.github/workflows/nightly.yaml
.github/workflows/pull-requests.yaml
.github/workflows/weekly.yaml
mysql-test/suite/secondary_engine/r/shannon_params.result
mysql-test/suite/secondary_engine/t/shannon_params.test
storage/rapid_engine/handler/ha_shannon_rapid.cc

feat(rapid):to check params

---

mysql-test/collections/disabled.def
storage/rapid_engine/imcs/chunk.cpp
storage/rapid_engine/imcs/chunk.h
storage/rapid_engine/imcs/cu.cpp
storage/rapid_engine/imcs/cu.h
storage/rapid_engine/imcs/imcs.cpp
storage/rapid_engine/imcs/imcs.h
storage/rapid_engine/imcs/imcu.cpp
storage/rapid_engine/imcs/table.cpp
storage/rapid_engine/imcs/table.h

_fix parallel load._
- Fixes #290

feat(rapid): to fix parall load

---

.github/workflows/nightly.yaml

_skip some timeout cases on arm._
- Fixes #458

feat(workflow): skip some timeout cases on arm

---

.github/workflows/pull-requests.yaml
storage/rapid_engine/imcs/imcs.cpp
storage/rapid_engine/imcs/table.cpp
storage/rapid_engine/imcs/table.h

feat(rapid):refine rapid engine

---

.github/workflows/nightly.yaml
mysql-test/suite/secondary_engine/r/shannon_large_data_index.result
mysql-test/suite/secondary_engine/t/shannon_large_data_index.test
storage/rapid_engine/imcs/data_table.cpp
storage/rapid_engine/imcs/data_table.h
storage/rapid_engine/imcs/index/art/iterator.h
storage/rapid_engine/imcs/index/iterator.h

feat(mtr): add test cases

---

.github/workflows/weekly.yaml

feat(workflow):update weekly workflow

---

storage/rapid_engine/imcs/index/art/art.cpp
storage/rapid_engine/imcs/index/art/art.h

feat(rapid): add concurrent control

---

sql/handler.cc
sql/handler.h
storage/rapid_engine/handler/ha_shannon_rapid.cc
storage/rapid_engine/handler/ha_shannon_rapid.h
storage/rapid_engine/handler/ha_shannon_rapidpart.cc
storage/rapid_engine/handler/ha_shannon_rapidpart.h

add some hooks for DML/select
- Fixes #476

feat(rapid): add hooks

---

storage/rapid_engine/imcs/index/art/art.cpp

feat(rapid): refine art swit-case

---

storage/rapid_engine/compress/algorithms.cpp
storage/rapid_engine/compress/algorithms.h
storage/rapid_engine/compress/dictionary/dictionary.cpp
storage/rapid_engine/compress/dictionary/dictionary.h
storage/rapid_engine/utils/utils.h

feat(rapid):refactor compression

---

.github/workflows/nightly.yaml
.github/workflows/weekly.yaml

feat(workflow): fixup wrong params

---

.github/workflows/nightly.yaml
.github/workflows/weekly.yaml
mysql-test/collections/skip-tests.arm

feat(workflow): refine MTR run option

---

storage/rapid_engine/handler/ha_shannon_rapid.cc
storage/rapid_engine/optimizer/optimizer.cpp
storage/rapid_engine/optimizer/optimizer.h
storage/rapid_engine/optimizer/path/access_path.cpp
storage/rapid_engine/optimizer/path/access_path.h
storage/rapid_engine/statistics/statistics.cpp
storage/rapid_engine/statistics/statistics.h

_vectorized execution framework._

feat(rapid): vectorized execution framework

---

storage/rapid_engine/executor/iterators/table_scan_iterator.cpp
storage/rapid_engine/imcs/data_table.cpp
storage/rapid_engine/utils/utils.h

feat(rapid): minor changes for table scan iterator

---

ml/ml_embedding.cpp
ml/ml_embedding.h
mysql-test/suite/secondary_engine/r/shannon_embedding.result
mysql-test/suite/secondary_engine/t/shannon_embedding.test
scripts/sys_schema/procedures/ml_embed_table.sql

feat(shannon):embedding table

---

extra/llm-models/README.md

feat(shannon): add model default dirs

---

ml/infra_component/llm_generate.cpp
ml/infra_component/llm_generate.h
ml/ml_generate.cpp
mysql-test/r/initialize.result
mysql-test/r/ps_sys_upgrade.result

feat(rapid): fix up llm generation

---

.github/workflows/pull-requests.yaml

feat(workflow): add asan option for workflow

---

mysql-test/suite/sysschema/r/all_sys_objects_exist.result

feat(mtr): fix mtr result

---

mysql-test/collections/skip-tests.arm

feat(mtr): fixup mtr results on arm

---

extra/tokenizer-ffi/Cargo.toml
extra/tokenizer-ffi/build.rs
extra/tokenizer-ffi/include/tokenizer_ffi.h
extra/tokenizer-ffi/src/lib.rs
ml/infra_component/llm_generate.cpp
ml/infra_component/llm_generate.h
ml/infra_component/tokenizer.h

_using HF compatible apply chat template._
- Fixes #528

feat(ML): add apply chat template as HF

---

sql/item_sum.h
sql/join_optimizer/access_path.h
storage/rapid_engine/CMakeLists.txt
storage/rapid_engine/executor/iterators/aggregate_iterator.cpp
storage/rapid_engine/executor/iterators/aggregate_iterator.h
storage/rapid_engine/executor/iterators/hash_join_iterator.cpp
storage/rapid_engine/executor/iterators/hash_join_iterator.h
storage/rapid_engine/executor/iterators/iterator.h
storage/rapid_engine/include/rapid_const.h
storage/rapid_engine/optimizer/optimizer.cpp
storage/rapid_engine/optimizer/optimizer.h
storage/rapid_engine/optimizer/path/access_path.cpp
storage/rapid_engine/optimizer/path/access_path.h
storage/rapid_engine/utils/SIMD.h
storage/rapid_engine/utils/SIMD_Impl.h

_add vectorized aggregate iterator._
- Fixes #536

feat(shannon): add vectorized aggregate iterator

---

.github/workflows/nightly.yaml
.github/workflows/weekly.yaml

Running disk space when running nightly workflow, therefore, we remove some mtr suites.
Fixes:#538
_Running disk space when running nightly workflow, therefore, we remove some mtr suites.._
- Fixes #538

feat(workflow): adjust nightly workflow

---

storage/rapid_engine/optimizer/optimizer.cpp

fix table scan optimization vectorized flag not be set.
_fix table scan optimization vectorized flag not be set.._

feat(shannon): fix table scan optimize
